project:
  type: website
  output-dir: docs   

website:
  title: "my_personal_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true

